Put a note next to '100% reproducible'
apptainer/apptainer.org pull request #13
Opened 2021-12-15 15:01 UTC by rhpvorderman

This was discussed in https://github.com/apptainer/apptainer/issues/64 .

I don't know if the * and the comment in `<small>` are well-placed on the main page. At least stating that singularity can be configured to be reproducible instead of claiming it is 100% reproducible is more accurate and it will hopefully lead people to use the `--containall` flag if 100% reproducibility is a requirement.

Alternative route:
Remove the * and the docs link and add a chapter in the documentation called `Reproducibility` that highlights the `--containall` flag. That is perhaps the preferrable route.

2021-12-15 16:02 UTC, DrDaveD requested changes

2021-12-15 16:02 UTC, DrDaveD commented on src/pages/index.js
> +              Apptainer/Singularity is the most widely used container system for HPC. It is designed to execute applications at bare-metal performance while being secure, portable, and can be configu
In this context I'd rather not change the main text (the new suggested wording is quite awkward) but instead have the asterisk say "*To ensure complete reproducibility use the --containall flag, ..."

2021-12-15 16:05 UTC, DrDaveD commented
To pass the DCO see check follow the instructions in [apptainer CONTRIBUTING.md](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md#getting-started).

2021-12-15 16:07 UTC, DrDaveD commented
Oh, and now I see the alternative suggestion you have for a new chapter in the documentation, and I do like that better than a change to the home page.  Would you be willing to do that instead?

2021-12-17 11:47 UTC, rhpvorderman commented
Sure. I will have a look at it when I have the time!

2023-11-13 05:07 UTC, ressonix commented
Going to go ahead and close this now that the new site is up and this is no longer relevant.

2023-11-13 05:07 UTC, closed without merging